create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  lead_key text not null unique,
  name text,
  email text,
  phone text,
  address text,
  city text,
  state text,
  zip text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists leads_state_idx on public.leads (state);
create index if not exists leads_zip_idx on public.leads (zip);
create index if not exists leads_email_idx on public.leads (email);

alter table public.leads enable row level security;

-- The application queries through the Vercel API using the server-side secret key.
-- No direct browser access to this table is granted here.
-- IMPORTANT: never expose SUPABASE_SECRET_KEY / service_role key to the browser.
